### ISSUE TITLE
Error opening spreadsheets with non ascii characters

### ISSUE THREAD

**Issue by aldeano** [edpop/smart-tools#4]
When i open a spreadsheet with accents or another non ascii caracter i've got this error:

```
Traceback (most recent call last):
  File "C:/Users/jorge.munoz/.qgis2/python/plugins\SpreadsheetLayers\widgets    \SpreadsheetLayersDialog.py", line 807, in accept
if not self.writeVrt():
  File "C:/Users/jorge.munoz/.qgis2/python/plugins\SpreadsheetLayers\widgets\SpreadsheetLayersDialog.py", line 769, in writeVrt
    msgBox.setText("The file {} already exist.".format(vrtPath))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 44: ordinal not in range(128)


Versión de Python:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


Versión de QGIS:
2.10.1-Pisa Pisa, d20c5b7
```

Working in win7 64 bits with all updates available.

**Comment by edpop** [comment]
I don't have any valid files for this plugin, but i tried to load empty file with path contains cyrillic symbols and got a similar error in same file 276: self.messageBar.pushMessage('Could not open {}'.format(filePath) -> UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-11: ordinal not in range(128).
Then i changed this string to unicode -> self.messageBar.pushMessage(u'Could not open {}'.format(filePath). Now messageBar writes me correct message with cyrillic symbols. Try to make same changes in other output messages.

**Comment by aldeano** [comment]
By changing the strings to unicode in lines 276, 298, 584, 769, 779 and 796 i can open files with non ascii characters.
