### ISSUE TITLE
Experimental or not? does not work on 2.8

### ISSUE THREAD

**Issue by luipir** [edpop/smart-tools#5]
Hi

I noticed that this plugin does not work on 2.8 version (at least my compiled version giving me python: invalid syntax)
It works with qgis master.

should be marked as experimental or it's only a my local problem?

regards

**Comment by edpop** [comment]
Thank for your message.

I tried use all functions on 2.6, 2.8 and 2.10 versions and did not get any errors. Only on download  in 2.8 QGIS tells me this error. Unfortunate that it can't be debugged in local version.

Marked as experimental.

**Comment by luipir** [comment]
seems append only during first installation... after rerun qgis, the "invalid syntax" error disappear.
Just tested with 2.8.3 compiled version. BTW an interesting plugin :)

**Comment by luipir** [comment]
probably the problem is related with the package name... more or less the same as in:
https://translate.google.com/translate?hl=en&sl=sv&tl=en&u=http%3A%2F%2Fgeosupportsystem.wordpress.com%2F
change it from smart-editing-tools to smart_editing_tools would solve the installation warning

this is a PEP8 error message see more info on:
http://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them

**Comment by edpop** [comment]
Thank you, the problem was in plugin directory.
Unfortunate, http://plugins.qgis.org does not allow me to add a new version with different dir names.

**Comment by luipir** [comment]
I suggest to ask to Alessandro Pasotti  https://github.com/elpaso to ask how to solve this prolem... or simply remove ad add again the plugin
